[package]
name = "cpu_v2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
digital-design-code = { path = "../core" }
paste = "1.0.11"
minifb = "0.24"
