// Bounded self-checking Icarus testbench for the rasterizer leaf.
//
// The TB prints the `RAST <seq> SCENE <name>` markers and drives the serial
// vertex beat stream; the DUT emits the TRI/PREFETCH/QUAD/TILE_END/DONE
// trace lines at the events themselves. Scenes are strictly serialized: the
// next scene starts only after the DUT pulsed `scene_done` for the previous
// one. The sink throttle pattern is selected at runtime (+THROTTLE=0|1|2:
// always ready, periodic 3/2, every third cycle) and only changes timing,
// never the value sequence.
//
// Scene vectors come from `raster_vectors.vh` (generated by the Rust
// integration test from `rastersim::scenes`) when compiled with
// -DRASTER_COSIM; otherwise two small embedded smoke scenes run, so the
// leaf's `verify_verilog_with_iverilog` smoke test stands alone.
`timescale 1ns/1ps
module tb #(parameter PIXELS_PER_CYCLE = 2, parameter SCANLINE = 0);
reg clk = 1'b0;
always #5 clk = ~clk;

integer cycles = 0;
integer cycle_limit = 2000000;
always @(posedge clk) begin
    cycles = cycles + 1;
    if (cycles > cycle_limit) begin
        $display("raster watchdog: clip=%0d setup=%0d tile=%0b(%0d,%0d) quad=%0d in/co/tri/tile/quad=%0d/%0d/%0d/%0d/%0d prefetch=%0d active=%0b ended=%0b",
                 dut.clip_state, dut.setup_state, dut.t_valid, dut.tx, dut.ty,
                 dut.quad_state, dut.in_count, dut.co_count, dut.tri_count,
                 dut.tj_count, dut.qd_count, dut.prefetch_outstanding,
                 dut.scene_active, dut.input_ended);
        $fatal(1, "raster testbench cycle limit exceeded");
    end
end

reg reset = 1;
reg input_valid = 0;
reg input_last = 0;
reg [31:0] input_data = 0;
wire input_ready;
reg sink_ready = 1;
integer throttle_mode = 0;

wire quad_valid;
wire quad_is_tile_end;
wire quad_is_retire_marker;
wire retire_marker_draw;
wire [31:0] quad_tri;
wire [15:0] quad_tile;
wire [15:0] quad_x;
wire [15:0] quad_y;
wire [3:0] quad_mask;
wire prefetch_acquire_valid;
wire [15:0] prefetch_acquire_tile;
wire scene_done;
reg held_valid = 0;
reg [85:0] held_item = 0;
wire [85:0] output_item = {quad_is_retire_marker, quad_is_tile_end,
                           quad_tri, quad_tile, quad_x, quad_y, quad_mask};

CpuV3GpuRaster #(.VIEWPORT_ONLY(0), .PIXELS_PER_CYCLE(PIXELS_PER_CYCLE),
                .SCANLINE(SCANLINE)) dut(
    .clk(clk), .reset(reset),
    .input_valid(input_valid), .input_last(input_last),
    .input_data(input_data), .input_ready(input_ready),
    .sink_ready(sink_ready),
    .quad_valid(quad_valid), .quad_is_tile_end(quad_is_tile_end),
    .quad_is_retire_marker(quad_is_retire_marker),
    .retire_marker_draw(retire_marker_draw),
    .quad_tri(quad_tri), .quad_tile(quad_tile),
    .quad_x(quad_x), .quad_y(quad_y), .quad_mask(quad_mask),
    .prefetch_acquire_ready((cycles % 7) != 0),
    .prefetch_acquire_valid(prefetch_acquire_valid),
    .prefetch_acquire_tile(prefetch_acquire_tile),
    .scene_done(scene_done));

// Check the actual ready/valid stream as well as the DUT's enqueue trace.
always @(posedge clk) begin
    if (reset) begin
        held_valid <= 0;
    end else begin
        if (held_valid && (!quad_valid || output_item !== held_item))
            $fatal(1, "raster output changed while stalled");
        held_valid <= quad_valid && !sink_ready;
        if (quad_valid && !sink_ready)
            held_item <= output_item;
        if (quad_valid && sink_ready) begin
            if (quad_is_retire_marker)
                $display("RAST_OUT RETIRE_MARKER %0d DRAW %0d",
                         quad_tri, retire_marker_draw);
            else if (quad_is_tile_end)
                $display("RAST_OUT TILE_END %0d", quad_tile);
            else
                $display("RAST_OUT QUAD %0d %0d %0d %0x",
                         quad_tri, quad_x, quad_y, quad_mask);
        end
    end
end

// Throttle patterns match `rasteremu::Throttle` (0 = Always,
// 1 = Periodic { run: 3, stall: 2 }, 2 = Third).
always @(*) begin
    case (throttle_mode)
        1: sink_ready = (cycles % 5) < 3;
        2: sink_ready = (cycles % 3) == 0;
        default: sink_ready = 1'b1;
    endcase
end

integer scenes_started = 0;
integer scenes_done = 0;
integer tb_seq = 0;

always @(negedge clk) begin
    if (scene_done === 1'b1)
        scenes_done = scenes_done + 1;
end

task send_beat;
    input [31:0] data;
    input last;
    begin
        @(negedge clk);
        input_data = data;
        input_last = last;
        input_valid = 1'b1;
        @(posedge clk);
        while (!input_ready) @(posedge clk);
        @(negedge clk);
        input_valid = 1'b0;
        input_last = 1'b0;
    end
endtask

task drive_tri;
    input [31:0] x0;
    input [31:0] y0;
    input [31:0] z0;
    input [31:0] w0;
    input [31:0] x1;
    input [31:0] y1;
    input [31:0] z1;
    input [31:0] w1;
    input [31:0] x2;
    input [31:0] y2;
    input [31:0] z2;
    input [31:0] w2;
    input last;
    begin
        send_beat(x0, 1'b0);
        send_beat(y0, 1'b0);
        send_beat(z0, 1'b0);
        send_beat(w0, 1'b0);
        send_beat(x1, 1'b0);
        send_beat(y1, 1'b0);
        send_beat(z1, 1'b0);
        send_beat(w1, 1'b0);
        send_beat(x2, 1'b0);
        send_beat(y2, 1'b0);
        send_beat(z2, 1'b0);
        send_beat(w2, last);
    end
endtask

task scene_begin;
    input [8*48:1] name;
    begin
        while (scenes_done < scenes_started) @(negedge clk);
        scenes_started = scenes_started + 1;
        @(negedge clk);
        $display("RAST %0d SCENE %0s", tb_seq, name);
        tb_seq = tb_seq + 1;
    end
endtask

initial begin
    if (!$value$plusargs("THROTTLE=%d", throttle_mode))
        throttle_mode = 0;
    if (!$value$plusargs("CYCLE_LIMIT=%d", cycle_limit))
        cycle_limit = 2000000;
    repeat (4) @(negedge clk);
    reset = 0;
`ifdef RASTER_COSIM
`include "raster_vectors.vh"
`else
    // Smoke: one trivial-accept front face, one near-plane clip fan.
    scene_begin("smoke-accept");
    drive_tri(32'hffff0000, 32'h00010000, 32'h00008000, 32'h00020000,
              32'h00010000, 32'h00010000, 32'h00008000, 32'h00020000,
              32'h00000000, 32'hffff0000, 32'h00008000, 32'h00020000, 1'b1);
    scene_begin("smoke-clip-near");
    drive_tri(32'h00000000, 32'h00008000, 32'hffff8000, 32'h00010000,
              32'h00010000, 32'hffff8000, 32'h00008000, 32'h00010000,
              32'hffff0000, 32'hffff8000, 32'h00008000, 32'h00010000, 1'b1);
`endif
    while (scenes_done < scenes_started) @(negedge clk);
    repeat (8) @(negedge clk);
    if (quad_valid !== 1'b0)
        $fatal(1, "raster quad stream not drained at end of run");
    $display("DIGITAL_DESIGN_PASS");
    $finish;
end

endmodule
