module CpuV3FpuRegisterRam (
    input wire clk,
    input wire write_enable,
    input wire [8:0] write_address,
    input wire [31:0] write_data,
    input wire [8:0] read_a_address,
    input wire [8:0] read_b_address,
    output wire [31:0] read_a_data,
    output wire [31:0] read_b_data
);

// Two identical 512x32 storage mirrors, each written through one synchronous
// port and read through one synchronous port. No ramstyle attribute is used:
// the plain inference is meant to let Gowin map every mirror to a single SDPB
// pseudo-dual-port BSRAM (one write port plus one read port). The write port
// broadcasts the same address and data into both mirrors, read port A serves
// mirror 0 and read port B serves mirror 1. Reads have one cycle of latency
// and read-first semantics: when a write and a read hit the same address in
// one cycle, both read ports still return the old word.
//
// Address map: physical addresses 0..63 alias architectural registers
// F0..F63, and 64..511 are the hidden LUT region used by RCP/RSQRT/SINCOS.
// The parent is responsible for forcing the top three address bits of
// architectural accesses to zero; this leaf never muxes an address.
reg [31:0] mirror_0 [0:511];
reg [31:0] mirror_1 [0:511];
reg [31:0] read_a_data_r = 0;
reg [31:0] read_b_data_r = 0;
integer initial_word;
// LUT_INIT_BEGIN (generated by fpu_lut_codegen; do not edit)
initial begin
    for (initial_word = 0; initial_word < 512; initial_word = initial_word + 1) begin
        mirror_0[initial_word] = 0;
        mirror_1[initial_word] = 0;
    end
    mirror_0[64] = 32'h00010000; mirror_0[65] = 32'h0000FE04; mirror_0[66] = 32'h0000FC10; mirror_0[67] = 32'h0000FA23;
    mirror_0[68] = 32'h0000F83E; mirror_0[69] = 32'h0000F660; mirror_0[70] = 32'h0000F48A; mirror_0[71] = 32'h0000F2BA;
    mirror_0[72] = 32'h0000F0F1; mirror_0[73] = 32'h0000EF2F; mirror_0[74] = 32'h0000ED73; mirror_0[75] = 32'h0000EBBE;
    mirror_0[76] = 32'h0000EA0F; mirror_0[77] = 32'h0000E866; mirror_0[78] = 32'h0000E6C3; mirror_0[79] = 32'h0000E526;
    mirror_0[80] = 32'h0000E38E; mirror_0[81] = 32'h0000E1FC; mirror_0[82] = 32'h0000E070; mirror_0[83] = 32'h0000DEE9;
    mirror_0[84] = 32'h0000DD68; mirror_0[85] = 32'h0000DBEB; mirror_0[86] = 32'h0000DA74; mirror_0[87] = 32'h0000D902;
    mirror_0[88] = 32'h0000D794; mirror_0[89] = 32'h0000D62C; mirror_0[90] = 32'h0000D4C7; mirror_0[91] = 32'h0000D368;
    mirror_0[92] = 32'h0000D20D; mirror_0[93] = 32'h0000D0B7; mirror_0[94] = 32'h0000CF64; mirror_0[95] = 32'h0000CE17;
    mirror_0[96] = 32'h0000CCCD; mirror_0[97] = 32'h0000CB87; mirror_0[98] = 32'h0000CA46; mirror_0[99] = 32'h0000C908;
    mirror_0[100] = 32'h0000C7CE; mirror_0[101] = 32'h0000C698; mirror_0[102] = 32'h0000C566; mirror_0[103] = 32'h0000C437;
    mirror_0[104] = 32'h0000C30C; mirror_0[105] = 32'h0000C1E5; mirror_0[106] = 32'h0000C0C1; mirror_0[107] = 32'h0000BFA0;
    mirror_0[108] = 32'h0000BE83; mirror_0[109] = 32'h0000BD69; mirror_0[110] = 32'h0000BC52; mirror_0[111] = 32'h0000BB3F;
    mirror_0[112] = 32'h0000BA2F; mirror_0[113] = 32'h0000B921; mirror_0[114] = 32'h0000B817; mirror_0[115] = 32'h0000B710;
    mirror_0[116] = 32'h0000B60B; mirror_0[117] = 32'h0000B50A; mirror_0[118] = 32'h0000B40B; mirror_0[119] = 32'h0000B30F;
    mirror_0[120] = 32'h0000B216; mirror_0[121] = 32'h0000B120; mirror_0[122] = 32'h0000B02C; mirror_0[123] = 32'h0000AF3B;
    mirror_0[124] = 32'h0000AE4C; mirror_0[125] = 32'h0000AD60; mirror_0[126] = 32'h0000AC77; mirror_0[127] = 32'h0000AB8F;
    mirror_0[128] = 32'h0000AAAB; mirror_0[129] = 32'h0000A9C8; mirror_0[130] = 32'h0000A8E8; mirror_0[131] = 32'h0000A80B;
    mirror_0[132] = 32'h0000A72F; mirror_0[133] = 32'h0000A656; mirror_0[134] = 32'h0000A57F; mirror_0[135] = 32'h0000A4AA;
    mirror_0[136] = 32'h0000A3D7; mirror_0[137] = 32'h0000A306; mirror_0[138] = 32'h0000A238; mirror_0[139] = 32'h0000A16B;
    mirror_0[140] = 32'h0000A0A1; mirror_0[141] = 32'h00009FD8; mirror_0[142] = 32'h00009F11; mirror_0[143] = 32'h00009E4D;
    mirror_0[144] = 32'h00009D8A; mirror_0[145] = 32'h00009CC9; mirror_0[146] = 32'h00009C0A; mirror_0[147] = 32'h00009B4C;
    mirror_0[148] = 32'h00009A91; mirror_0[149] = 32'h000099D7; mirror_0[150] = 32'h0000991F; mirror_0[151] = 32'h00009869;
    mirror_0[152] = 32'h000097B4; mirror_0[153] = 32'h00009701; mirror_0[154] = 32'h00009650; mirror_0[155] = 32'h000095A0;
    mirror_0[156] = 32'h000094F2; mirror_0[157] = 32'h00009446; mirror_0[158] = 32'h0000939B; mirror_0[159] = 32'h000092F1;
    mirror_0[160] = 32'h00009249; mirror_0[161] = 32'h000091A3; mirror_0[162] = 32'h000090FE; mirror_0[163] = 32'h0000905A;
    mirror_0[164] = 32'h00008FB8; mirror_0[165] = 32'h00008F17; mirror_0[166] = 32'h00008E78; mirror_0[167] = 32'h00008DDA;
    mirror_0[168] = 32'h00008D3E; mirror_0[169] = 32'h00008CA3; mirror_0[170] = 32'h00008C09; mirror_0[171] = 32'h00008B70;
    mirror_0[172] = 32'h00008AD9; mirror_0[173] = 32'h00008A43; mirror_0[174] = 32'h000089AE; mirror_0[175] = 32'h0000891B;
    mirror_0[176] = 32'h00008889; mirror_0[177] = 32'h000087F8; mirror_0[178] = 32'h00008768; mirror_0[179] = 32'h000086D9;
    mirror_0[180] = 32'h0000864C; mirror_0[181] = 32'h000085BF; mirror_0[182] = 32'h00008534; mirror_0[183] = 32'h000084AA;
    mirror_0[184] = 32'h00008421; mirror_0[185] = 32'h00008399; mirror_0[186] = 32'h00008312; mirror_0[187] = 32'h0000828D;
    mirror_0[188] = 32'h00008208; mirror_0[189] = 32'h00008185; mirror_0[190] = 32'h00008102; mirror_0[191] = 32'h00008081;
    mirror_0[193] = 32'h00000192; mirror_0[194] = 32'h00000324; mirror_0[195] = 32'h000004B6; mirror_0[196] = 32'h00000648;
    mirror_0[197] = 32'h000007DA; mirror_0[198] = 32'h0000096C; mirror_0[199] = 32'h00000AFE; mirror_0[200] = 32'h00000C90;
    mirror_0[201] = 32'h00000E21; mirror_0[202] = 32'h00000FB3; mirror_0[203] = 32'h00001144; mirror_0[204] = 32'h000012D5;
    mirror_0[205] = 32'h00001466; mirror_0[206] = 32'h000015F7; mirror_0[207] = 32'h00001787; mirror_0[208] = 32'h00001918;
    mirror_0[209] = 32'h00001AA8; mirror_0[210] = 32'h00001C38; mirror_0[211] = 32'h00001DC7; mirror_0[212] = 32'h00001F56;
    mirror_0[213] = 32'h000020E5; mirror_0[214] = 32'h00002274; mirror_0[215] = 32'h00002402; mirror_0[216] = 32'h00002590;
    mirror_0[217] = 32'h0000271E; mirror_0[218] = 32'h000028AB; mirror_0[219] = 32'h00002A38; mirror_0[220] = 32'h00002BC4;
    mirror_0[221] = 32'h00002D50; mirror_0[222] = 32'h00002EDC; mirror_0[223] = 32'h00003067; mirror_0[224] = 32'h000031F1;
    mirror_0[225] = 32'h0000337C; mirror_0[226] = 32'h00003505; mirror_0[227] = 32'h0000368E; mirror_0[228] = 32'h00003817;
    mirror_0[229] = 32'h0000399F; mirror_0[230] = 32'h00003B27; mirror_0[231] = 32'h00003CAE; mirror_0[232] = 32'h00003E34;
    mirror_0[233] = 32'h00003FBA; mirror_0[234] = 32'h0000413F; mirror_0[235] = 32'h000042C3; mirror_0[236] = 32'h00004447;
    mirror_0[237] = 32'h000045CB; mirror_0[238] = 32'h0000474D; mirror_0[239] = 32'h000048CF; mirror_0[240] = 32'h00004A50;
    mirror_0[241] = 32'h00004BD1; mirror_0[242] = 32'h00004D50; mirror_0[243] = 32'h00004ECF; mirror_0[244] = 32'h0000504D;
    mirror_0[245] = 32'h000051CB; mirror_0[246] = 32'h00005348; mirror_0[247] = 32'h000054C3; mirror_0[248] = 32'h0000563E;
    mirror_0[249] = 32'h000057B9; mirror_0[250] = 32'h00005932; mirror_0[251] = 32'h00005AAA; mirror_0[252] = 32'h00005C22;
    mirror_0[253] = 32'h00005D99; mirror_0[254] = 32'h00005F0F; mirror_0[255] = 32'h00006084; mirror_0[256] = 32'h000061F8;
    mirror_0[257] = 32'h0000636B; mirror_0[258] = 32'h000064DD; mirror_0[259] = 32'h0000664E; mirror_0[260] = 32'h000067BE;
    mirror_0[261] = 32'h0000692D; mirror_0[262] = 32'h00006A9B; mirror_0[263] = 32'h00006C08; mirror_0[264] = 32'h00006D74;
    mirror_0[265] = 32'h00006EDF; mirror_0[266] = 32'h00007049; mirror_0[267] = 32'h000071B2; mirror_0[268] = 32'h0000731A;
    mirror_0[269] = 32'h00007480; mirror_0[270] = 32'h000075E6; mirror_0[271] = 32'h0000774A; mirror_0[272] = 32'h000078AD;
    mirror_0[273] = 32'h00007A10; mirror_0[274] = 32'h00007B70; mirror_0[275] = 32'h00007CD0; mirror_0[276] = 32'h00007E2F;
    mirror_0[277] = 32'h00007F8C; mirror_0[278] = 32'h000080E8; mirror_0[279] = 32'h00008243; mirror_0[280] = 32'h0000839C;
    mirror_0[281] = 32'h000084F5; mirror_0[282] = 32'h0000864C; mirror_0[283] = 32'h000087A1; mirror_0[284] = 32'h000088F6;
    mirror_0[285] = 32'h00008A49; mirror_0[286] = 32'h00008B9A; mirror_0[287] = 32'h00008CEB; mirror_0[288] = 32'h00008E3A;
    mirror_0[289] = 32'h00008F88; mirror_0[290] = 32'h000090D4; mirror_0[291] = 32'h0000921F; mirror_0[292] = 32'h00009368;
    mirror_0[293] = 32'h000094B0; mirror_0[294] = 32'h000095F7; mirror_0[295] = 32'h0000973C; mirror_0[296] = 32'h00009880;
    mirror_0[297] = 32'h000099C2; mirror_0[298] = 32'h00009B03; mirror_0[299] = 32'h00009C42; mirror_0[300] = 32'h00009D80;
    mirror_0[301] = 32'h00009EBC; mirror_0[302] = 32'h00009FF7; mirror_0[303] = 32'h0000A130; mirror_0[304] = 32'h0000A268;
    mirror_0[305] = 32'h0000A39E; mirror_0[306] = 32'h0000A4D2; mirror_0[307] = 32'h0000A605; mirror_0[308] = 32'h0000A736;
    mirror_0[309] = 32'h0000A866; mirror_0[310] = 32'h0000A994; mirror_0[311] = 32'h0000AAC1; mirror_0[312] = 32'h0000ABEB;
    mirror_0[313] = 32'h0000AD14; mirror_0[314] = 32'h0000AE3C; mirror_0[315] = 32'h0000AF62; mirror_0[316] = 32'h0000B086;
    mirror_0[317] = 32'h0000B1A8; mirror_0[318] = 32'h0000B2C9; mirror_0[319] = 32'h0000B3E8; mirror_0[320] = 32'h0000B505;
    mirror_0[321] = 32'h0000B620; mirror_0[322] = 32'h0000B73A; mirror_0[323] = 32'h0000B852; mirror_0[324] = 32'h0000B968;
    mirror_0[325] = 32'h0000BA7D; mirror_0[326] = 32'h0000BB8F; mirror_0[327] = 32'h0000BCA0; mirror_0[328] = 32'h0000BDAF;
    mirror_0[329] = 32'h0000BEBC; mirror_0[330] = 32'h0000BFC7; mirror_0[331] = 32'h0000C0D1; mirror_0[332] = 32'h0000C1D8;
    mirror_0[333] = 32'h0000C2DE; mirror_0[334] = 32'h0000C3E2; mirror_0[335] = 32'h0000C4E4; mirror_0[336] = 32'h0000C5E4;
    mirror_0[337] = 32'h0000C6E2; mirror_0[338] = 32'h0000C7DE; mirror_0[339] = 32'h0000C8D9; mirror_0[340] = 32'h0000C9D1;
    mirror_0[341] = 32'h0000CAC7; mirror_0[342] = 32'h0000CBBC; mirror_0[343] = 32'h0000CCAE; mirror_0[344] = 32'h0000CD9F;
    mirror_0[345] = 32'h0000CE8E; mirror_0[346] = 32'h0000CF7A; mirror_0[347] = 32'h0000D065; mirror_0[348] = 32'h0000D14D;
    mirror_0[349] = 32'h0000D234; mirror_0[350] = 32'h0000D318; mirror_0[351] = 32'h0000D3FB; mirror_0[352] = 32'h0000D4DB;
    mirror_0[353] = 32'h0000D5BA; mirror_0[354] = 32'h0000D696; mirror_0[355] = 32'h0000D770; mirror_0[356] = 32'h0000D848;
    mirror_0[357] = 32'h0000D91E; mirror_0[358] = 32'h0000D9F2; mirror_0[359] = 32'h0000DAC4; mirror_0[360] = 32'h0000DB94;
    mirror_0[361] = 32'h0000DC62; mirror_0[362] = 32'h0000DD2D; mirror_0[363] = 32'h0000DDF7; mirror_0[364] = 32'h0000DEBE;
    mirror_0[365] = 32'h0000DF83; mirror_0[366] = 32'h0000E046; mirror_0[367] = 32'h0000E107; mirror_0[368] = 32'h0000E1C6;
    mirror_0[369] = 32'h0000E282; mirror_0[370] = 32'h0000E33C; mirror_0[371] = 32'h0000E3F4; mirror_0[372] = 32'h0000E4AA;
    mirror_0[373] = 32'h0000E55E; mirror_0[374] = 32'h0000E610; mirror_0[375] = 32'h0000E6BF; mirror_0[376] = 32'h0000E76C;
    mirror_0[377] = 32'h0000E817; mirror_0[378] = 32'h0000E8BF; mirror_0[379] = 32'h0000E966; mirror_0[380] = 32'h0000EA0A;
    mirror_0[381] = 32'h0000EAAB; mirror_0[382] = 32'h0000EB4B; mirror_0[383] = 32'h0000EBE8; mirror_0[384] = 32'h0000EC83;
    mirror_0[385] = 32'h0000ED1C; mirror_0[386] = 32'h0000EDB3; mirror_0[387] = 32'h0000EE47; mirror_0[388] = 32'h0000EED9;
    mirror_0[389] = 32'h0000EF68; mirror_0[390] = 32'h0000EFF5; mirror_0[391] = 32'h0000F080; mirror_0[392] = 32'h0000F109;
    mirror_0[393] = 32'h0000F18F; mirror_0[394] = 32'h0000F213; mirror_0[395] = 32'h0000F295; mirror_0[396] = 32'h0000F314;
    mirror_0[397] = 32'h0000F391; mirror_0[398] = 32'h0000F40C; mirror_0[399] = 32'h0000F484; mirror_0[400] = 32'h0000F4FA;
    mirror_0[401] = 32'h0000F56E; mirror_0[402] = 32'h0000F5DF; mirror_0[403] = 32'h0000F64E; mirror_0[404] = 32'h0000F6BA;
    mirror_0[405] = 32'h0000F724; mirror_0[406] = 32'h0000F78C; mirror_0[407] = 32'h0000F7F1; mirror_0[408] = 32'h0000F854;
    mirror_0[409] = 32'h0000F8B4; mirror_0[410] = 32'h0000F913; mirror_0[411] = 32'h0000F96E; mirror_0[412] = 32'h0000F9C8;
    mirror_0[413] = 32'h0000FA1F; mirror_0[414] = 32'h0000FA73; mirror_0[415] = 32'h0000FAC5; mirror_0[416] = 32'h0000FB15;
    mirror_0[417] = 32'h0000FB62; mirror_0[418] = 32'h0000FBAD; mirror_0[419] = 32'h0000FBF5; mirror_0[420] = 32'h0000FC3B;
    mirror_0[421] = 32'h0000FC7F; mirror_0[422] = 32'h0000FCC0; mirror_0[423] = 32'h0000FCFE; mirror_0[424] = 32'h0000FD3B;
    mirror_0[425] = 32'h0000FD74; mirror_0[426] = 32'h0000FDAC; mirror_0[427] = 32'h0000FDE1; mirror_0[428] = 32'h0000FE13;
    mirror_0[429] = 32'h0000FE43; mirror_0[430] = 32'h0000FE71; mirror_0[431] = 32'h0000FE9C; mirror_0[432] = 32'h0000FEC4;
    mirror_0[433] = 32'h0000FEEB; mirror_0[434] = 32'h0000FF0E; mirror_0[435] = 32'h0000FF30; mirror_0[436] = 32'h0000FF4E;
    mirror_0[437] = 32'h0000FF6B; mirror_0[438] = 32'h0000FF85; mirror_0[439] = 32'h0000FF9C; mirror_0[440] = 32'h0000FFB1;
    mirror_0[441] = 32'h0000FFC4; mirror_0[442] = 32'h0000FFD4; mirror_0[443] = 32'h0000FFE1; mirror_0[444] = 32'h0000FFEC;
    mirror_0[445] = 32'h0000FFF5; mirror_0[446] = 32'h0000FFFB; mirror_0[447] = 32'h0000FFFF; mirror_0[448] = 32'h00010000;
    mirror_1[64] = 32'h00010000; mirror_1[65] = 32'h0000FE83; mirror_1[66] = 32'h0000FD0D; mirror_1[67] = 32'h0000FB9E;
    mirror_1[68] = 32'h0000FA34; mirror_1[69] = 32'h0000F8D0; mirror_1[70] = 32'h0000F773; mirror_1[71] = 32'h0000F61B;
    mirror_1[72] = 32'h0000F4C8; mirror_1[73] = 32'h0000F37B; mirror_1[74] = 32'h0000F234; mirror_1[75] = 32'h0000F0F1;
    mirror_1[76] = 32'h0000EFB3; mirror_1[77] = 32'h0000EE7A; mirror_1[78] = 32'h0000ED46; mirror_1[79] = 32'h0000EC17;
    mirror_1[80] = 32'h0000EAEC; mirror_1[81] = 32'h0000E9C5; mirror_1[82] = 32'h0000E8A3; mirror_1[83] = 32'h0000E785;
    mirror_1[84] = 32'h0000E66B; mirror_1[85] = 32'h0000E555; mirror_1[86] = 32'h0000E443; mirror_1[87] = 32'h0000E335;
    mirror_1[88] = 32'h0000E22A; mirror_1[89] = 32'h0000E123; mirror_1[90] = 32'h0000E020; mirror_1[91] = 32'h0000DF20;
    mirror_1[92] = 32'h0000DE23; mirror_1[93] = 32'h0000DD2A; mirror_1[94] = 32'h0000DC34; mirror_1[95] = 32'h0000DB41;
    mirror_1[96] = 32'h0000DA51; mirror_1[97] = 32'h0000D965; mirror_1[98] = 32'h0000D87B; mirror_1[99] = 32'h0000D794;
    mirror_1[100] = 32'h0000D6B0; mirror_1[101] = 32'h0000D5CF; mirror_1[102] = 32'h0000D4F1; mirror_1[103] = 32'h0000D415;
    mirror_1[104] = 32'h0000D33C; mirror_1[105] = 32'h0000D266; mirror_1[106] = 32'h0000D192; mirror_1[107] = 32'h0000D0C0;
    mirror_1[108] = 32'h0000CFF1; mirror_1[109] = 32'h0000CF25; mirror_1[110] = 32'h0000CE5A; mirror_1[111] = 32'h0000CD93;
    mirror_1[112] = 32'h0000CCCD; mirror_1[113] = 32'h0000CC09; mirror_1[114] = 32'h0000CB48; mirror_1[115] = 32'h0000CA89;
    mirror_1[116] = 32'h0000C9CC; mirror_1[117] = 32'h0000C911; mirror_1[118] = 32'h0000C858; mirror_1[119] = 32'h0000C7A0;
    mirror_1[120] = 32'h0000C6EB; mirror_1[121] = 32'h0000C638; mirror_1[122] = 32'h0000C587; mirror_1[123] = 32'h0000C4D7;
    mirror_1[124] = 32'h0000C42A; mirror_1[125] = 32'h0000C37E; mirror_1[126] = 32'h0000C2D4; mirror_1[127] = 32'h0000C22B;
    mirror_1[128] = 32'h0000C185; mirror_1[129] = 32'h0000C0E0; mirror_1[130] = 32'h0000C03C; mirror_1[131] = 32'h0000BF9A;
    mirror_1[132] = 32'h0000BEFA; mirror_1[133] = 32'h0000BE5B; mirror_1[134] = 32'h0000BDBE; mirror_1[135] = 32'h0000BD23;
    mirror_1[136] = 32'h0000BC89; mirror_1[137] = 32'h0000BBF0; mirror_1[138] = 32'h0000BB59; mirror_1[139] = 32'h0000BAC3;
    mirror_1[140] = 32'h0000BA2F; mirror_1[141] = 32'h0000B99C; mirror_1[142] = 32'h0000B90A; mirror_1[143] = 32'h0000B879;
    mirror_1[144] = 32'h0000B7EA; mirror_1[145] = 32'h0000B75D; mirror_1[146] = 32'h0000B6D0; mirror_1[147] = 32'h0000B645;
    mirror_1[148] = 32'h0000B5BB; mirror_1[149] = 32'h0000B532; mirror_1[150] = 32'h0000B4AB; mirror_1[151] = 32'h0000B424;
    mirror_1[152] = 32'h0000B39F; mirror_1[153] = 32'h0000B31B; mirror_1[154] = 32'h0000B298; mirror_1[155] = 32'h0000B216;
    mirror_1[156] = 32'h0000B196; mirror_1[157] = 32'h0000B116; mirror_1[158] = 32'h0000B097; mirror_1[159] = 32'h0000B01A;
    mirror_1[160] = 32'h0000AF9D; mirror_1[161] = 32'h0000AF22; mirror_1[162] = 32'h0000AEA7; mirror_1[163] = 32'h0000AE2E;
    mirror_1[164] = 32'h0000ADB6; mirror_1[165] = 32'h0000AD3E; mirror_1[166] = 32'h0000ACC8; mirror_1[167] = 32'h0000AC52;
    mirror_1[168] = 32'h0000ABDD; mirror_1[169] = 32'h0000AB6A; mirror_1[170] = 32'h0000AAF7; mirror_1[171] = 32'h0000AA85;
    mirror_1[172] = 32'h0000AA14; mirror_1[173] = 32'h0000A9A4; mirror_1[174] = 32'h0000A934; mirror_1[175] = 32'h0000A8C6;
    mirror_1[176] = 32'h0000A858; mirror_1[177] = 32'h0000A7EB; mirror_1[178] = 32'h0000A77F; mirror_1[179] = 32'h0000A714;
    mirror_1[180] = 32'h0000A6AA; mirror_1[181] = 32'h0000A640; mirror_1[182] = 32'h0000A5D8; mirror_1[183] = 32'h0000A570;
    mirror_1[184] = 32'h0000A508; mirror_1[185] = 32'h0000A4A2; mirror_1[186] = 32'h0000A43C; mirror_1[187] = 32'h0000A3D7;
    mirror_1[188] = 32'h0000A373; mirror_1[189] = 32'h0000A30F; mirror_1[190] = 32'h0000A2AC; mirror_1[191] = 32'h0000A24A;
    mirror_1[192] = 32'h0000A1E9; mirror_1[193] = 32'h0000A188; mirror_1[194] = 32'h0000A128; mirror_1[195] = 32'h0000A0C8;
    mirror_1[196] = 32'h0000A069; mirror_1[197] = 32'h0000A00B; mirror_1[198] = 32'h00009FAE; mirror_1[199] = 32'h00009F51;
    mirror_1[200] = 32'h00009EF5; mirror_1[201] = 32'h00009E99; mirror_1[202] = 32'h00009E3E; mirror_1[203] = 32'h00009DE4;
    mirror_1[204] = 32'h00009D8A; mirror_1[205] = 32'h00009D31; mirror_1[206] = 32'h00009CD8; mirror_1[207] = 32'h00009C80;
    mirror_1[208] = 32'h00009C29; mirror_1[209] = 32'h00009BD2; mirror_1[210] = 32'h00009B7B; mirror_1[211] = 32'h00009B26;
    mirror_1[212] = 32'h00009AD0; mirror_1[213] = 32'h00009A7C; mirror_1[214] = 32'h00009A28; mirror_1[215] = 32'h000099D4;
    mirror_1[216] = 32'h00009981; mirror_1[217] = 32'h0000992F; mirror_1[218] = 32'h000098DD; mirror_1[219] = 32'h0000988B;
    mirror_1[220] = 32'h0000983A; mirror_1[221] = 32'h000097EA; mirror_1[222] = 32'h0000979A; mirror_1[223] = 32'h0000974A;
    mirror_1[224] = 32'h000096FB; mirror_1[225] = 32'h000096AC; mirror_1[226] = 32'h0000965E; mirror_1[227] = 32'h00009611;
    mirror_1[228] = 32'h000095C4; mirror_1[229] = 32'h00009577; mirror_1[230] = 32'h0000952B; mirror_1[231] = 32'h000094DF;
    mirror_1[232] = 32'h00009494; mirror_1[233] = 32'h00009449; mirror_1[234] = 32'h000093FF; mirror_1[235] = 32'h000093B5;
    mirror_1[236] = 32'h0000936B; mirror_1[237] = 32'h00009322; mirror_1[238] = 32'h000092D9; mirror_1[239] = 32'h00009291;
    mirror_1[240] = 32'h00009249; mirror_1[241] = 32'h00009202; mirror_1[242] = 32'h000091BB; mirror_1[243] = 32'h00009174;
    mirror_1[244] = 32'h0000912E; mirror_1[245] = 32'h000090E8; mirror_1[246] = 32'h000090A3; mirror_1[247] = 32'h0000905D;
    mirror_1[248] = 32'h00009019; mirror_1[249] = 32'h00008FD4; mirror_1[250] = 32'h00008F91; mirror_1[251] = 32'h00008F4D;
    mirror_1[252] = 32'h00008F0A; mirror_1[253] = 32'h00008EC7; mirror_1[254] = 32'h00008E85; mirror_1[255] = 32'h00008E43;
    mirror_1[256] = 32'h00008E01; mirror_1[257] = 32'h00008DBF; mirror_1[258] = 32'h00008D7E; mirror_1[259] = 32'h00008D3E;
    mirror_1[260] = 32'h00008CFD; mirror_1[261] = 32'h00008CBD; mirror_1[262] = 32'h00008C7E; mirror_1[263] = 32'h00008C3F;
    mirror_1[264] = 32'h00008C00; mirror_1[265] = 32'h00008BC1; mirror_1[266] = 32'h00008B83; mirror_1[267] = 32'h00008B45;
    mirror_1[268] = 32'h00008B07; mirror_1[269] = 32'h00008ACA; mirror_1[270] = 32'h00008A8D; mirror_1[271] = 32'h00008A50;
    mirror_1[272] = 32'h00008A13; mirror_1[273] = 32'h000089D7; mirror_1[274] = 32'h0000899C; mirror_1[275] = 32'h00008960;
    mirror_1[276] = 32'h00008925; mirror_1[277] = 32'h000088EA; mirror_1[278] = 32'h000088AF; mirror_1[279] = 32'h00008875;
    mirror_1[280] = 32'h0000883B; mirror_1[281] = 32'h00008801; mirror_1[282] = 32'h000087C8; mirror_1[283] = 32'h0000878F;
    mirror_1[284] = 32'h00008756; mirror_1[285] = 32'h0000871D; mirror_1[286] = 32'h000086E5; mirror_1[287] = 32'h000086AD;
    mirror_1[288] = 32'h00008675; mirror_1[289] = 32'h0000863E; mirror_1[290] = 32'h00008606; mirror_1[291] = 32'h000085CF;
    mirror_1[292] = 32'h00008599; mirror_1[293] = 32'h00008562; mirror_1[294] = 32'h0000852C; mirror_1[295] = 32'h000084F6;
    mirror_1[296] = 32'h000084C1; mirror_1[297] = 32'h0000848B; mirror_1[298] = 32'h00008456; mirror_1[299] = 32'h00008421;
    mirror_1[300] = 32'h000083EC; mirror_1[301] = 32'h000083B8; mirror_1[302] = 32'h00008384; mirror_1[303] = 32'h00008350;
    mirror_1[304] = 32'h0000831C; mirror_1[305] = 32'h000082E9; mirror_1[306] = 32'h000082B5; mirror_1[307] = 32'h00008282;
    mirror_1[308] = 32'h00008250; mirror_1[309] = 32'h0000821D; mirror_1[310] = 32'h000081EB; mirror_1[311] = 32'h000081B9;
    mirror_1[312] = 32'h00008187; mirror_1[313] = 32'h00008155; mirror_1[314] = 32'h00008124; mirror_1[315] = 32'h000080F3;
    mirror_1[316] = 32'h000080C2; mirror_1[317] = 32'h00008091; mirror_1[318] = 32'h00008060; mirror_1[319] = 32'h00008030;
end
// LUT_INIT_END

always @(posedge clk) begin
    if (write_enable)
        mirror_0[write_address] <= write_data;
    read_a_data_r <= mirror_0[read_a_address];
end

always @(posedge clk) begin
    if (write_enable)
        mirror_1[write_address] <= write_data;
    read_b_data_r <= mirror_1[read_b_address];
end

assign read_a_data = read_a_data_r;
assign read_b_data = read_b_data_r;

endmodule
