module CpuV3FpuRegisterRam (
    input wire clk,
    input wire write_enable,
    input wire [8:0] write_address,
    input wire [31:0] write_data,
    input wire [8:0] read_a_address,
    input wire [8:0] read_b_address,
    output wire [31:0] read_a_data,
    output wire [31:0] read_b_data
);

// Two identical 512x32 storage mirrors, each written through one synchronous
// port and read through one synchronous port. No ramstyle attribute is used:
// the plain inference is meant to let Gowin map every mirror to a single SDPB
// pseudo-dual-port BSRAM (one write port plus one read port). The write port
// broadcasts the same address and data into both mirrors, read port A serves
// mirror 0 and read port B serves mirror 1. Reads have one cycle of latency
// and read-first semantics: when a write and a read hit the same address in
// one cycle, both read ports still return the old word.
//
// Address map: physical addresses 0..63 alias architectural registers
// F0..F63, and 64..511 are the hidden LUT region used by RCP/RSQRT/SINCOS.
// The parent is responsible for forcing the top three address bits of
// architectural accesses to zero; this leaf never muxes an address.
reg [31:0] mirror_0 [0:511];
reg [31:0] mirror_1 [0:511];
reg [31:0] read_a_data_r = 0;
reg [31:0] read_b_data_r = 0;
integer initial_word;
// LUT_INIT_BEGIN (generated by fpu_lut_codegen; do not edit)
initial begin
    for (initial_word = 0; initial_word < 512; initial_word = initial_word + 1) begin
        mirror_0[initial_word] = 0;
        mirror_1[initial_word] = 0;
    end
    mirror_0[128] = 32'h04090000; mirror_0[129] = 32'h0418FE04; mirror_0[130] = 32'h0426FC10; mirror_0[131] = 32'h0436FA23;
    mirror_0[132] = 32'h0444F83E; mirror_0[133] = 32'h0454F660; mirror_0[134] = 32'h0460F48A; mirror_0[135] = 32'h046EF2BA;
    mirror_0[136] = 32'h047CF0F1; mirror_0[137] = 32'h0488EF2F; mirror_0[138] = 32'h0496ED73; mirror_0[139] = 32'h04A2EBBE;
    mirror_0[140] = 32'h04AEEA0F; mirror_0[141] = 32'h04BAE866; mirror_0[142] = 32'h04C6E6C3; mirror_0[143] = 32'h04D0E526;
    mirror_0[144] = 32'h04DCE38E; mirror_0[145] = 32'h04E8E1FC; mirror_0[146] = 32'h04F2E070; mirror_0[147] = 32'h04FEDEE9;
    mirror_0[148] = 32'h0506DD68; mirror_0[149] = 32'h0512DBEB; mirror_0[150] = 32'h051CDA74; mirror_0[151] = 32'h0524D902;
    mirror_0[152] = 32'h0530D794; mirror_0[153] = 32'h0536D62C; mirror_0[154] = 32'h0542D4C7; mirror_0[155] = 32'h054AD368;
    mirror_0[156] = 32'h0554D20D; mirror_0[157] = 32'h055AD0B7; mirror_0[158] = 32'h0566CF64; mirror_0[159] = 32'h056CCE17;
    mirror_0[160] = 32'h0574CCCD; mirror_0[161] = 32'h057ECB87; mirror_0[162] = 32'h0584CA46; mirror_0[163] = 32'h058CC908;
    mirror_0[164] = 32'h0594C7CE; mirror_0[165] = 32'h059CC698; mirror_0[166] = 32'h05A2C566; mirror_0[167] = 32'h05AAC437;
    mirror_0[168] = 32'h05B2C30C; mirror_0[169] = 32'h05B8C1E5; mirror_0[170] = 32'h05BEC0C1; mirror_0[171] = 32'h05C6BFA0;
    mirror_0[172] = 32'h05CCBE83; mirror_0[173] = 32'h05D2BD69; mirror_0[174] = 32'h05DABC52; mirror_0[175] = 32'h05E0BB3F;
    mirror_0[176] = 32'h05E4BA2F; mirror_0[177] = 32'h05ECB921; mirror_0[178] = 32'h05F2B817; mirror_0[179] = 32'h05F6B710;
    mirror_0[180] = 32'h05FEB60B; mirror_0[181] = 32'h0602B50A; mirror_0[182] = 32'h0608B40B; mirror_0[183] = 32'h060EB30F;
    mirror_0[184] = 32'h0614B216; mirror_0[185] = 32'h0618B120; mirror_0[186] = 32'h061EB02C; mirror_0[187] = 32'h0622AF3B;
    mirror_0[188] = 32'h0628AE4C; mirror_0[189] = 32'h062EAD60; mirror_0[190] = 32'h0630AC77; mirror_0[191] = 32'h0638AB8F;
    mirror_0[192] = 32'h063AAAAB; mirror_0[193] = 32'h0640A9C8; mirror_0[194] = 32'h0646A8E8; mirror_0[195] = 32'h0648A80B;
    mirror_0[196] = 32'h064EA72F; mirror_0[197] = 32'h0652A656; mirror_0[198] = 32'h0656A57F; mirror_0[199] = 32'h065AA4AA;
    mirror_0[200] = 32'h065EA3D7; mirror_0[201] = 32'h0664A306; mirror_0[202] = 32'h0666A238; mirror_0[203] = 32'h066CA16B;
    mirror_0[204] = 32'h066EA0A1; mirror_0[205] = 32'h06729FD8; mirror_0[206] = 32'h06789F11; mirror_0[207] = 32'h067A9E4D;
    mirror_0[208] = 32'h067E9D8A; mirror_0[209] = 32'h06829CC9; mirror_0[210] = 32'h06849C0A; mirror_0[211] = 32'h068A9B4C;
    mirror_0[212] = 32'h068C9A91; mirror_0[213] = 32'h069099D7; mirror_0[214] = 32'h0694991F; mirror_0[215] = 32'h06969869;
    mirror_0[216] = 32'h069A97B4; mirror_0[217] = 32'h069E9701; mirror_0[218] = 32'h06A09650; mirror_0[219] = 32'h06A495A0;
    mirror_0[220] = 32'h06A894F2; mirror_0[221] = 32'h06AA9446; mirror_0[222] = 32'h06AC939B; mirror_0[223] = 32'h06B092F1;
    mirror_0[224] = 32'h06B49249; mirror_0[225] = 32'h06B691A3; mirror_0[226] = 32'h06B890FE; mirror_0[227] = 32'h06BC905A;
    mirror_0[228] = 32'h06BE8FB8; mirror_0[229] = 32'h06C28F17; mirror_0[230] = 32'h06C48E78; mirror_0[231] = 32'h06C88DDA;
    mirror_0[232] = 32'h06CA8D3E; mirror_0[233] = 32'h06CC8CA3; mirror_0[234] = 32'h06CE8C09; mirror_0[235] = 32'h06D28B70;
    mirror_0[236] = 32'h06D48AD9; mirror_0[237] = 32'h06D68A43; mirror_0[238] = 32'h06DA89AE; mirror_0[239] = 32'h06DC891B;
    mirror_0[240] = 32'h06DE8889; mirror_0[241] = 32'h06E087F8; mirror_0[242] = 32'h06E28768; mirror_0[243] = 32'h06E686D9;
    mirror_0[244] = 32'h06E6864C; mirror_0[245] = 32'h06EA85BF; mirror_0[246] = 32'h06EC8534; mirror_0[247] = 32'h06EE84AA;
    mirror_0[248] = 32'h06F08421; mirror_0[249] = 32'h06F28399; mirror_0[250] = 32'h06F68312; mirror_0[251] = 32'h06F6828D;
    mirror_0[252] = 32'h06FA8208; mirror_0[253] = 32'h06FA8185; mirror_0[254] = 32'h06FE8102; mirror_0[255] = 32'h06FE8081;
    mirror_0[256] = 32'h03240000; mirror_0[257] = 32'h03240192; mirror_0[258] = 32'h03240324; mirror_0[259] = 32'h032404B6;
    mirror_0[260] = 32'h03240648; mirror_0[261] = 32'h032407DA; mirror_0[262] = 32'h0324096C; mirror_0[263] = 32'h03240AFE;
    mirror_0[264] = 32'h03220C90; mirror_0[265] = 32'h03240E21; mirror_0[266] = 32'h03220FB3; mirror_0[267] = 32'h03221144;
    mirror_0[268] = 32'h032212D5; mirror_0[269] = 32'h03221466; mirror_0[270] = 32'h032015F7; mirror_0[271] = 32'h03221787;
    mirror_0[272] = 32'h03201918; mirror_0[273] = 32'h03201AA8; mirror_0[274] = 32'h031E1C38; mirror_0[275] = 32'h031E1DC7;
    mirror_0[276] = 32'h031E1F56; mirror_0[277] = 32'h031E20E5; mirror_0[278] = 32'h031C2274; mirror_0[279] = 32'h031C2402;
    mirror_0[280] = 32'h031C2590; mirror_0[281] = 32'h031A271E; mirror_0[282] = 32'h031A28AB; mirror_0[283] = 32'h03182A38;
    mirror_0[284] = 32'h03182BC4; mirror_0[285] = 32'h03182D50; mirror_0[286] = 32'h03162EDC; mirror_0[287] = 32'h03143067;
    mirror_0[288] = 32'h031631F1; mirror_0[289] = 32'h0312337C; mirror_0[290] = 32'h03123505; mirror_0[291] = 32'h0312368E;
    mirror_0[292] = 32'h03103817; mirror_0[293] = 32'h0310399F; mirror_0[294] = 32'h030E3B27; mirror_0[295] = 32'h030C3CAE;
    mirror_0[296] = 32'h030C3E34; mirror_0[297] = 32'h030A3FBA; mirror_0[298] = 32'h0308413F; mirror_0[299] = 32'h030842C3;
    mirror_0[300] = 32'h03084447; mirror_0[301] = 32'h030445CB; mirror_0[302] = 32'h0304474D; mirror_0[303] = 32'h030248CF;
    mirror_0[304] = 32'h03024A50; mirror_0[305] = 32'h02FE4BD1; mirror_0[306] = 32'h02FE4D50; mirror_0[307] = 32'h02FC4ECF;
    mirror_0[308] = 32'h02FC504D; mirror_0[309] = 32'h02FA51CB; mirror_0[310] = 32'h02F65348; mirror_0[311] = 32'h02F654C3;
    mirror_0[312] = 32'h02F6563E; mirror_0[313] = 32'h02F257B9; mirror_0[314] = 32'h02F05932; mirror_0[315] = 32'h02F05AAA;
    mirror_0[316] = 32'h02EE5C22; mirror_0[317] = 32'h02EC5D99; mirror_0[318] = 32'h02EA5F0F; mirror_0[319] = 32'h02E86084;
    mirror_0[320] = 32'h02E661F8; mirror_0[321] = 32'h02E4636B; mirror_0[322] = 32'h02E264DD; mirror_0[323] = 32'h02E0664E;
    mirror_0[324] = 32'h02DE67BE; mirror_0[325] = 32'h02DC692D; mirror_0[326] = 32'h02DA6A9B; mirror_0[327] = 32'h02D86C08;
    mirror_0[328] = 32'h02D66D74; mirror_0[329] = 32'h02D46EDF; mirror_0[330] = 32'h02D27049; mirror_0[331] = 32'h02D071B2;
    mirror_0[332] = 32'h02CC731A; mirror_0[333] = 32'h02CC7480; mirror_0[334] = 32'h02C875E6; mirror_0[335] = 32'h02C6774A;
    mirror_0[336] = 32'h02C678AD; mirror_0[337] = 32'h02C07A10; mirror_0[338] = 32'h02C07B70; mirror_0[339] = 32'h02BE7CD0;
    mirror_0[340] = 32'h02BA7E2F; mirror_0[341] = 32'h02B87F8C; mirror_0[342] = 32'h02B680E8; mirror_0[343] = 32'h02B28243;
    mirror_0[344] = 32'h02B2839C; mirror_0[345] = 32'h02AE84F5; mirror_0[346] = 32'h02AA864C; mirror_0[347] = 32'h02AA87A1;
    mirror_0[348] = 32'h02A688F6; mirror_0[349] = 32'h02A28A49; mirror_0[350] = 32'h02A28B9A; mirror_0[351] = 32'h029E8CEB;
    mirror_0[352] = 32'h029C8E3A; mirror_0[353] = 32'h02988F88; mirror_0[354] = 32'h029690D4; mirror_0[355] = 32'h0292921F;
    mirror_0[356] = 32'h02909368; mirror_0[357] = 32'h028E94B0; mirror_0[358] = 32'h028A95F7; mirror_0[359] = 32'h0288973C;
    mirror_0[360] = 32'h02849880; mirror_0[361] = 32'h028299C2; mirror_0[362] = 32'h027E9B03; mirror_0[363] = 32'h027C9C42;
    mirror_0[364] = 32'h02789D80; mirror_0[365] = 32'h02769EBC; mirror_0[366] = 32'h02729FF7; mirror_0[367] = 32'h0270A130;
    mirror_0[368] = 32'h026CA268; mirror_0[369] = 32'h0268A39E; mirror_0[370] = 32'h0266A4D2; mirror_0[371] = 32'h0262A605;
    mirror_0[372] = 32'h0260A736; mirror_0[373] = 32'h025CA866; mirror_0[374] = 32'h025AA994; mirror_0[375] = 32'h0254AAC1;
    mirror_0[376] = 32'h0252ABEB; mirror_0[377] = 32'h0250AD14; mirror_0[378] = 32'h024CAE3C; mirror_0[379] = 32'h0248AF62;
    mirror_0[380] = 32'h0244B086; mirror_0[381] = 32'h0242B1A8; mirror_0[382] = 32'h023EB2C9; mirror_0[383] = 32'h023AB3E8;
    mirror_0[384] = 32'h0236B505; mirror_0[385] = 32'h0234B620; mirror_0[386] = 32'h0230B73A; mirror_0[387] = 32'h022CB852;
    mirror_0[388] = 32'h022AB968; mirror_0[389] = 32'h0224BA7D; mirror_0[390] = 32'h0222BB8F; mirror_0[391] = 32'h021EBCA0;
    mirror_0[392] = 32'h021ABDAF; mirror_0[393] = 32'h0216BEBC; mirror_0[394] = 32'h0214BFC7; mirror_0[395] = 32'h020EC0D1;
    mirror_0[396] = 32'h020CC1D8; mirror_0[397] = 32'h0208C2DE; mirror_0[398] = 32'h0204C3E2; mirror_0[399] = 32'h0200C4E4;
    mirror_0[400] = 32'h01FCC5E4; mirror_0[401] = 32'h01F8C6E2; mirror_0[402] = 32'h01F6C7DE; mirror_0[403] = 32'h01F0C8D9;
    mirror_0[404] = 32'h01ECC9D1; mirror_0[405] = 32'h01EACAC7; mirror_0[406] = 32'h01E4CBBC; mirror_0[407] = 32'h01E2CCAE;
    mirror_0[408] = 32'h01DECD9F; mirror_0[409] = 32'h01D8CE8E; mirror_0[410] = 32'h01D6CF7A; mirror_0[411] = 32'h01D0D065;
    mirror_0[412] = 32'h01CED14D; mirror_0[413] = 32'h01C8D234; mirror_0[414] = 32'h01C6D318; mirror_0[415] = 32'h01C0D3FB;
    mirror_0[416] = 32'h01BED4DB; mirror_0[417] = 32'h01B8D5BA; mirror_0[418] = 32'h01B4D696; mirror_0[419] = 32'h01B0D770;
    mirror_0[420] = 32'h01ACD848; mirror_0[421] = 32'h01A8D91E; mirror_0[422] = 32'h01A4D9F2; mirror_0[423] = 32'h01A0DAC4;
    mirror_0[424] = 32'h019CDB94; mirror_0[425] = 32'h0196DC62; mirror_0[426] = 32'h0194DD2D; mirror_0[427] = 32'h018EDDF7;
    mirror_0[428] = 32'h018ADEBE; mirror_0[429] = 32'h0186DF83; mirror_0[430] = 32'h0182E046; mirror_0[431] = 32'h017EE107;
    mirror_0[432] = 32'h0178E1C6; mirror_0[433] = 32'h0174E282; mirror_0[434] = 32'h0170E33C; mirror_0[435] = 32'h016CE3F4;
    mirror_0[436] = 32'h0168E4AA; mirror_0[437] = 32'h0164E55E; mirror_0[438] = 32'h015EE610; mirror_0[439] = 32'h015AE6BF;
    mirror_0[440] = 32'h0156E76C; mirror_0[441] = 32'h0150E817; mirror_0[442] = 32'h014EE8BF; mirror_0[443] = 32'h0148E966;
    mirror_0[444] = 32'h0142EA0A; mirror_0[445] = 32'h0140EAAB; mirror_0[446] = 32'h013AEB4B; mirror_0[447] = 32'h0136EBE8;
    mirror_0[448] = 32'h0132EC83; mirror_0[449] = 32'h012EED1C; mirror_0[450] = 32'h0128EDB3; mirror_0[451] = 32'h0124EE47;
    mirror_0[452] = 32'h011EEED9; mirror_0[453] = 32'h011AEF68; mirror_0[454] = 32'h0116EFF5; mirror_0[455] = 32'h0112F080;
    mirror_0[456] = 32'h010CF109; mirror_0[457] = 32'h0108F18F; mirror_0[458] = 32'h0104F213; mirror_0[459] = 32'h00FEF295;
    mirror_0[460] = 32'h00FAF314; mirror_0[461] = 32'h00F6F391; mirror_0[462] = 32'h00F0F40C; mirror_0[463] = 32'h00ECF484;
    mirror_0[464] = 32'h00E8F4FA; mirror_0[465] = 32'h00E2F56E; mirror_0[466] = 32'h00DEF5DF; mirror_0[467] = 32'h00D8F64E;
    mirror_0[468] = 32'h00D4F6BA; mirror_0[469] = 32'h00D0F724; mirror_0[470] = 32'h00CAF78C; mirror_0[471] = 32'h00C6F7F1;
    mirror_0[472] = 32'h00C0F854; mirror_0[473] = 32'h00BEF8B4; mirror_0[474] = 32'h00B6F913; mirror_0[475] = 32'h00B4F96E;
    mirror_0[476] = 32'h00AEF9C8; mirror_0[477] = 32'h00A8FA1F; mirror_0[478] = 32'h00A4FA73; mirror_0[479] = 32'h00A0FAC5;
    mirror_0[480] = 32'h009AFB15; mirror_0[481] = 32'h0096FB62; mirror_0[482] = 32'h0090FBAD; mirror_0[483] = 32'h008CFBF5;
    mirror_0[484] = 32'h0088FC3B; mirror_0[485] = 32'h0082FC7F; mirror_0[486] = 32'h007CFCC0; mirror_0[487] = 32'h007AFCFE;
    mirror_0[488] = 32'h0072FD3B; mirror_0[489] = 32'h0070FD74; mirror_0[490] = 32'h006AFDAC; mirror_0[491] = 32'h0064FDE1;
    mirror_0[492] = 32'h0060FE13; mirror_0[493] = 32'h005CFE43; mirror_0[494] = 32'h0056FE71; mirror_0[495] = 32'h0050FE9C;
    mirror_0[496] = 32'h004EFEC4; mirror_0[497] = 32'h0046FEEB; mirror_0[498] = 32'h0044FF0E; mirror_0[499] = 32'h003CFF30;
    mirror_0[500] = 32'h003AFF4E; mirror_0[501] = 32'h0034FF6B; mirror_0[502] = 32'h002EFF85; mirror_0[503] = 32'h002AFF9C;
    mirror_0[504] = 32'h0026FFB1; mirror_0[505] = 32'h0020FFC4; mirror_0[506] = 32'h001AFFD4; mirror_0[507] = 32'h0016FFE1;
    mirror_0[508] = 32'h0012FFEC; mirror_0[509] = 32'h000CFFF5; mirror_0[510] = 32'h0008FFFB; mirror_0[511] = 32'h0002FFFF;
    mirror_1[128] = 32'h06030000; mirror_1[129] = 32'h060AFF01; mirror_1[130] = 32'h060EFE06; mirror_1[131] = 32'h0614FD0D;
    mirror_1[132] = 32'h061AFC17; mirror_1[133] = 32'h0620FB24; mirror_1[134] = 32'h0624FA34; mirror_1[135] = 32'h062AF946;
    mirror_1[136] = 32'h0630F85B; mirror_1[137] = 32'h0634F773; mirror_1[138] = 32'h0638F68D; mirror_1[139] = 32'h063EF5A9;
    mirror_1[140] = 32'h0644F4C8; mirror_1[141] = 32'h0648F3EA; mirror_1[142] = 32'h064CF30E; mirror_1[143] = 32'h0650F234;
    mirror_1[144] = 32'h0656F15C; mirror_1[145] = 32'h0658F087; mirror_1[146] = 32'h065EEFB3; mirror_1[147] = 32'h0662EEE2;
    mirror_1[148] = 32'h0666EE13; mirror_1[149] = 32'h066CED46; mirror_1[150] = 32'h066EEC7C; mirror_1[151] = 32'h0672EBB3;
    mirror_1[152] = 32'h0676EAEC; mirror_1[153] = 32'h067AEA27; mirror_1[154] = 32'h067EE964; mirror_1[155] = 32'h0682E8A3;
    mirror_1[156] = 32'h0686E7E4; mirror_1[157] = 32'h0688E727; mirror_1[158] = 32'h068CE66B; mirror_1[159] = 32'h0690E5B1;
    mirror_1[160] = 32'h0694E4F9; mirror_1[161] = 32'h0696E443; mirror_1[162] = 32'h069AE38E; mirror_1[163] = 32'h069EE2DB;
    mirror_1[164] = 32'h06A0E22A; mirror_1[165] = 32'h06A4E17A; mirror_1[166] = 32'h06A8E0CC; mirror_1[167] = 32'h06AAE020;
    mirror_1[168] = 32'h06ACDF75; mirror_1[169] = 32'h06B0DECB; mirror_1[170] = 32'h06B2DE23; mirror_1[171] = 32'h06B6DD7C;
    mirror_1[172] = 32'h06BADCD7; mirror_1[173] = 32'h06BCDC34; mirror_1[174] = 32'h06BEDB92; mirror_1[175] = 32'h06C0DAF1;
    mirror_1[176] = 32'h06C4DA51; mirror_1[177] = 32'h06C6D9B3; mirror_1[178] = 32'h06CAD916; mirror_1[179] = 32'h06CCD87B;
    mirror_1[180] = 32'h06CED7E1; mirror_1[181] = 32'h06D0D748; mirror_1[182] = 32'h06D4D6B0; mirror_1[183] = 32'h06D6D61A;
    mirror_1[184] = 32'h06D8D585; mirror_1[185] = 32'h06DAD4F1; mirror_1[186] = 32'h06DED45E; mirror_1[187] = 32'h06DED3CD;
    mirror_1[188] = 32'h06E2D33C; mirror_1[189] = 32'h06E4D2AD; mirror_1[190] = 32'h06E6D21F; mirror_1[191] = 32'h06E8D192;
    mirror_1[192] = 32'h06EAD106; mirror_1[193] = 32'h06ECD07B; mirror_1[194] = 32'h06F0CFF1; mirror_1[195] = 32'h06F0CF69;
    mirror_1[196] = 32'h06F2CEE1; mirror_1[197] = 32'h06F6CE5A; mirror_1[198] = 32'h06F6CDD5; mirror_1[199] = 32'h06FACD50;
    mirror_1[200] = 32'h06FACCCD; mirror_1[201] = 32'h06FECC4A; mirror_1[202] = 32'h06FECBC9; mirror_1[203] = 32'h0700CB48;
    mirror_1[204] = 32'h0702CAC8; mirror_1[205] = 32'h0706CA49; mirror_1[206] = 32'h0706C9CC; mirror_1[207] = 32'h0708C94F;
    mirror_1[208] = 32'h070AC8D3; mirror_1[209] = 32'h070AC858; mirror_1[210] = 32'h070EC7DD; mirror_1[211] = 32'h070EC764;
    mirror_1[212] = 32'h0712C6EB; mirror_1[213] = 32'h0712C674; mirror_1[214] = 32'h0714C5FD; mirror_1[215] = 32'h0716C587;
    mirror_1[216] = 32'h0716C512; mirror_1[217] = 32'h071AC49D; mirror_1[218] = 32'h071AC42A; mirror_1[219] = 32'h071CC3B7;
    mirror_1[220] = 32'h071EC345; mirror_1[221] = 32'h071EC2D4; mirror_1[222] = 32'h0722C263; mirror_1[223] = 32'h0722C1F4;
    mirror_1[224] = 32'h0722C185; mirror_1[225] = 32'h0726C116; mirror_1[226] = 32'h0726C0A9; mirror_1[227] = 32'h0728C03C;
    mirror_1[228] = 32'h072ABFD0; mirror_1[229] = 32'h072ABF65; mirror_1[230] = 32'h072CBEFA; mirror_1[231] = 32'h072EBE90;
    mirror_1[232] = 32'h072EBE27; mirror_1[233] = 32'h0730BDBE; mirror_1[234] = 32'h0732BD56; mirror_1[235] = 32'h0734BCEF;
    mirror_1[236] = 32'h0734BC89; mirror_1[237] = 32'h0734BC23; mirror_1[238] = 32'h0738BBBD; mirror_1[239] = 32'h0738BB59;
    mirror_1[240] = 32'h0738BAF5; mirror_1[241] = 32'h073CBA91; mirror_1[242] = 32'h073ABA2F; mirror_1[243] = 32'h073EB9CC;
    mirror_1[244] = 32'h073EB96B; mirror_1[245] = 32'h073EB90A; mirror_1[246] = 32'h0742B8A9; mirror_1[247] = 32'h0740B84A;
    mirror_1[248] = 32'h0744B7EA; mirror_1[249] = 32'h0744B78C; mirror_1[250] = 32'h0744B72E; mirror_1[251] = 32'h0746B6D0;
    mirror_1[252] = 32'h0748B673; mirror_1[253] = 32'h0748B617; mirror_1[254] = 32'h074AB5BB; mirror_1[255] = 32'h074AB560;
    mirror_1[256] = 32'h0698B505; mirror_1[257] = 32'h069CB451; mirror_1[258] = 32'h06A0B39F; mirror_1[259] = 32'h06A4B2EF;
    mirror_1[260] = 32'h06AAB241; mirror_1[261] = 32'h06ACB196; mirror_1[262] = 32'h06B0B0EC; mirror_1[263] = 32'h06B2B044;
    mirror_1[264] = 32'h06B8AF9D; mirror_1[265] = 32'h06BAAEF9; mirror_1[266] = 32'h06C0AE56; mirror_1[267] = 32'h06C0ADB6;
    mirror_1[268] = 32'h06C6AD16; mirror_1[269] = 32'h06C8AC79; mirror_1[270] = 32'h06CCABDD; mirror_1[271] = 32'h06D0AB43;
    mirror_1[272] = 32'h06D2AAAB; mirror_1[273] = 32'h06D4AA14; mirror_1[274] = 32'h06DAA97E; mirror_1[275] = 32'h06DAA8EB;
    mirror_1[276] = 32'h06DEA858; mirror_1[277] = 32'h06E2A7C7; mirror_1[278] = 32'h06E4A738; mirror_1[279] = 32'h06E6A6AA;
    mirror_1[280] = 32'h06EAA61D; mirror_1[281] = 32'h06ECA592; mirror_1[282] = 32'h06F0A508; mirror_1[283] = 32'h06F2A480;
    mirror_1[284] = 32'h06F4A3F9; mirror_1[285] = 32'h06F6A373; mirror_1[286] = 32'h06FAA2EE; mirror_1[287] = 32'h06FCA26B;
    mirror_1[288] = 32'h06FEA1E9; mirror_1[289] = 32'h0700A168; mirror_1[290] = 32'h0702A0E8; mirror_1[291] = 32'h0706A069;
    mirror_1[292] = 32'h07089FEC; mirror_1[293] = 32'h070A9F70; mirror_1[294] = 32'h070C9EF5; mirror_1[295] = 32'h070E9E7B;
    mirror_1[296] = 32'h07109E02; mirror_1[297] = 32'h07129D8A; mirror_1[298] = 32'h07149D13; mirror_1[299] = 32'h07189C9D;
    mirror_1[300] = 32'h07189C29; mirror_1[301] = 32'h071A9BB5; mirror_1[302] = 32'h071C9B42; mirror_1[303] = 32'h07209AD0;
    mirror_1[304] = 32'h07209A60; mirror_1[305] = 32'h072299F0; mirror_1[306] = 32'h07249981; mirror_1[307] = 32'h07269913;
    mirror_1[308] = 32'h072898A6; mirror_1[309] = 32'h072A983A; mirror_1[310] = 32'h072A97CF; mirror_1[311] = 32'h072E9764;
    mirror_1[312] = 32'h072E96FB; mirror_1[313] = 32'h07329692; mirror_1[314] = 32'h0732962B; mirror_1[315] = 32'h073495C4;
    mirror_1[316] = 32'h0734955E; mirror_1[317] = 32'h073894F8; mirror_1[318] = 32'h07389494; mirror_1[319] = 32'h073A9430;
    mirror_1[320] = 32'h073C93CD; mirror_1[321] = 32'h073E936B; mirror_1[322] = 32'h073E930A; mirror_1[323] = 32'h074092A9;
    mirror_1[324] = 32'h07429249; mirror_1[325] = 32'h074491EA; mirror_1[326] = 32'h0744918C; mirror_1[327] = 32'h0746912E;
    mirror_1[328] = 32'h074690D1; mirror_1[329] = 32'h074A9074; mirror_1[330] = 32'h074A9019; mirror_1[331] = 32'h074C8FBE;
    mirror_1[332] = 32'h074C8F64; mirror_1[333] = 32'h074E8F0A; mirror_1[334] = 32'h07508EB1; mirror_1[335] = 32'h07508E59;
    mirror_1[336] = 32'h07528E01; mirror_1[337] = 32'h07528DAA; mirror_1[338] = 32'h07548D53; mirror_1[339] = 32'h07568CFD;
    mirror_1[340] = 32'h07588CA8; mirror_1[341] = 32'h07588C54; mirror_1[342] = 32'h07588C00; mirror_1[343] = 32'h075A8BAC;
    mirror_1[344] = 32'h075C8B59; mirror_1[345] = 32'h075C8B07; mirror_1[346] = 32'h075E8AB5; mirror_1[347] = 32'h075E8A64;
    mirror_1[348] = 32'h07608A13; mirror_1[349] = 32'h076289C3; mirror_1[350] = 32'h07628974; mirror_1[351] = 32'h07628925;
    mirror_1[352] = 32'h076688D6; mirror_1[353] = 32'h07648889; mirror_1[354] = 32'h0766883B; mirror_1[355] = 32'h076887EE;
    mirror_1[356] = 32'h076887A2; mirror_1[357] = 32'h076A8756; mirror_1[358] = 32'h076A870B; mirror_1[359] = 32'h076A86C0;
    mirror_1[360] = 32'h076C8675; mirror_1[361] = 32'h076E862B; mirror_1[362] = 32'h076E85E2; mirror_1[363] = 32'h076E8599;
    mirror_1[364] = 32'h07708550; mirror_1[365] = 32'h07728508; mirror_1[366] = 32'h077084C1; mirror_1[367] = 32'h07748479;
    mirror_1[368] = 32'h07728433; mirror_1[369] = 32'h077683EC; mirror_1[370] = 32'h077483A7; mirror_1[371] = 32'h07768361;
    mirror_1[372] = 32'h0778831C; mirror_1[373] = 32'h077682D8; mirror_1[374] = 32'h077A8293; mirror_1[375] = 32'h07788250;
    mirror_1[376] = 32'h077A820C; mirror_1[377] = 32'h077C81C9; mirror_1[378] = 32'h077C8187; mirror_1[379] = 32'h077C8145;
    mirror_1[380] = 32'h077E8103; mirror_1[381] = 32'h077E80C2; mirror_1[382] = 32'h077E8081; mirror_1[383] = 32'h07808040;
end
// LUT_INIT_END

always @(posedge clk) begin
    if (write_enable)
        mirror_0[write_address] <= write_data;
    read_a_data_r <= mirror_0[read_a_address];
end

always @(posedge clk) begin
    if (write_enable)
        mirror_1[write_address] <= write_data;
    read_b_data_r <= mirror_1[read_b_address];
end

assign read_a_data = read_a_data_r;
assign read_b_data = read_b_data_r;

endmodule
