//! Independent HDL registers versus Work, with a separate semantic queue.
use super::*;
use std::{
    collections::VecDeque,
    fmt::Write as _,
    process::{Command, Stdio},
    time::{Duration, Instant},
};

fn bounded(mut command: Command, path: &std::path::Path, stem: &str) {
    let out = path.join(format!("{stem}.out"));
    let err = path.join(format!("{stem}.err"));
    let mut child = command
        .stdout(Stdio::from(std::fs::File::create(&out).unwrap()))
        .stderr(Stdio::from(std::fs::File::create(&err).unwrap()))
        .spawn()
        .unwrap();
    let start = Instant::now();
    loop {
        if let Some(status) = child.try_wait().unwrap() {
            assert!(
                status.success(),
                "{} {}",
                std::fs::read_to_string(out).unwrap(),
                std::fs::read_to_string(err).unwrap()
            );
            break;
        }
        if start.elapsed() > Duration::from_secs(90) {
            let _ = child.kill();
            let _ = child.wait();
            panic!("Work HDL watchdog");
        }
        std::thread::sleep(Duration::from_millis(10));
    }
}

#[test]
#[ignore = "requires Icarus (IVERILOG_EXE/VVP_EXE)"]
fn work_ssram_prefetch_matches_independent_rtl_every_edge() {
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../target/sampling-foundation-20261007/work-rtl");
    std::fs::create_dir_all(&root).unwrap();
    std::fs::write(root.join("work.v"), crate::texture::rtl::work::verilog()).unwrap();
    for capacity in [2, 3, 16, 17, 32] {
        let mut work = Work::new(capacity).unwrap();
        let mut queue = VecDeque::<(Member, u8)>::new();
        let mut rng = 0x846f_1253_u32;
        let mut sent = 0;
        let mut received = 0;
        let mut concurrent = 0;
        let mut paused = 0;
        let mut reset_done = false;
        let mut tb = format!(
            "module tb; reg clk=0,reset=1,ce=0,in_valid=0,out_ready=0; reg [91:0] in_member=0; wire in_ready,out_valid,read_fire,write_fire,capture_fire,ack,fault; wire [91:0] out_member; wire [1:0] out_tap; gpu_v2_texture_work #(.DEPTH({capacity})) dut(.clk(clk),.reset(reset),.ce(ce),.in_valid(in_valid),.in_member(in_member),.in_ready(in_ready),.out_ready(out_ready),.out_valid(out_valid),.out_member(out_member),.out_tap(out_tap),.read_fire(read_fire),.write_fire(write_fire),.capture_fire(capture_fire),.ack(ack),.fault(fault)); initial begin #5; clk=1; #5; clk=0; reset=0;\n"
        );
        for wall in 0..10_000 {
            rng ^= rng << 13;
            rng ^= rng >> 17;
            rng ^= rng << 5;
            let old = work.snapshot();
            if !reset_done && old.materialized == capacity && old.loaded == HEADS {
                // Assert reset with both endpoints still trying to transfer.
                // At depth>2 unread source rows also remain in the same RAM.
                assert!(old.valid);
                if capacity > HEADS {
                    assert!(old.materialized > old.loaded);
                }
                let rows = work.rows.clone();
                work.reset();
                assert_eq!(work.rows, rows);
                queue.clear();
                sent = 0;
                received = 0;
                writeln!(tb,"reset=1;ce=1;in_valid=1;out_ready=1;#1;if({{in_ready,out_valid,read_fire,write_fire,capture_fire,ack}} !== 6'b0) $fatal(1,\"reset handshake\");#4;clk=1;#1;if(dut.count !== 0 || dut.head_count !== 0 || dut.head_valid !== 0) $fatal(1,\"reset state\");#4;clk=0;reset=0;in_valid=0;#1;if(out_valid !== 0) $fatal(1,\"stale reset output\");").unwrap();
                for (i, row) in rows.iter().enumerate().take(capacity) {
                    writeln!(
                        tb,
                        "if(dut.rows[{i}] !== 94'h{row:x}) $fatal(1,\"reset cleared RAM {i}\");"
                    )
                    .unwrap();
                }
                reset_done = true;
                continue;
            }
            let ce = !reset_done || rng & 3 != 0;
            let ready = reset_done && rng & 12 != 0;
            let offer = sent < 512 && (!reset_done || rng & 16 != 0);
            let mask = (sent % 15 + 1) as u8;
            // Literal semantic payload, not generated by Member::from_fields.
            let row = Member(
                u128::from(rng & 511)
                    | (u128::from(mask) << 36)
                    | ((sent % 64) as u128) << 84
                    | (u128::from(reset_done) << 75),
            );
            let put = ce && offer && old.materialized < capacity;
            let take = ce && ready && old.valid;
            let edge = work.tick(ce, put.then_some(row), take).unwrap();
            if let Some((actual, tap)) = edge.capture {
                let (expected, remaining) = queue.front_mut().unwrap();
                assert_eq!(actual, *expected);
                assert_eq!(tap, remaining.trailing_zeros() as u8);
                *remaining &= !(1 << tap);
                if *remaining == 0 {
                    queue.pop_front();
                    received += 1;
                }
            }
            if put {
                queue.push_back((row, mask));
                sent += 1;
            }
            assert_eq!(work.snapshot().materialized, queue.len());
            if !ce {
                assert_eq!(old, work.snapshot());
                paused += 1;
            }
            concurrent += usize::from(edge.read.is_some() && edge.ack);
            writeln!(
                tb,
                "ce={};in_valid={};out_ready={};in_member=92'h{:x};#1;",
                u8::from(ce),
                u8::from(offer),
                u8::from(ready),
                row.0
            )
            .unwrap();
            writeln!(tb, "if ({{in_ready,out_valid,read_fire,write_fire,capture_fire,ack,fault}} !== 7'b{}{}{}{}{}{}0) $fatal(1,\"flags {wall}\");",u8::from(old.materialized<capacity),u8::from(old.valid),u8::from(edge.read.is_some()),u8::from(edge.write.is_some()),u8::from(take),u8::from(edge.ack)).unwrap();
            if old.valid {
                writeln!(tb,"if(out_member !== 92'h{:x} || out_tap !== 2'd{}) $fatal(1,\"old head {wall}\");",old.payload.0,old.cursor).unwrap();
            }
            writeln!(tb, "#4;clk=1;#1;").unwrap();
            let new = work.snapshot();
            writeln!(tb,"if(dut.count !== {} || dut.head_count !== {} || dut.fetch_ptr !== {} || dut.reclaim_ptr !== {} || dut.write_ptr !== {} || dut.head_valid !== 2'd{} || dut.consume_head !== 1'd{} || dut.fill_head !== 1'd{}) $fatal(1,\"state {wall}\");",new.materialized,new.loaded,new.fetch,new.read,new.write,new.head_valid,new.consume_head,new.fill_head).unwrap();
            for h in 0..HEADS {
                if new.head_valid >> h & 1 != 0 {
                    writeln!(tb,"if(dut.heads[{h}] !== 92'h{:x} || dut.cursors[{h}] !== 2'd{}) $fatal(1,\"bank {h} edge {wall}\");",new.heads[h].0,new.cursors[h]).unwrap();
                }
            }
            writeln!(tb, "#4;clk=0;").unwrap();
            if received == 512 {
                break;
            }
        }
        assert_eq!((sent, received), (512, 512));
        assert!(concurrent > 0 && paused > 0 && reset_done);
        writeln!(tb,"$display(\"PASS Work depth={capacity} rows=512 concurrent={concurrent} paused={paused} occupied_reset=1\");$finish;end endmodule").unwrap();
        let stem = format!("work-{capacity}");
        std::fs::write(root.join(format!("{stem}_tb.v")), tb).unwrap();
        let mut compile =
            Command::new(std::env::var_os("IVERILOG_EXE").unwrap_or_else(|| "iverilog".into()));
        compile.current_dir(&root).args([
            "-g2012",
            "-s",
            "tb",
            "-o",
            &format!("{stem}.vvp"),
            "work.v",
            &format!("{stem}_tb.v"),
        ]);
        bounded(compile, &root, &format!("{stem}-compile"));
        let mut run = Command::new(std::env::var_os("VVP_EXE").unwrap_or_else(|| "vvp".into()));
        run.current_dir(&root).arg(format!("{stem}.vvp"));
        bounded(run, &root, &format!("{stem}-run"));
        let output = std::fs::read_to_string(root.join(format!("{stem}-run.out"))).unwrap();
        assert!(output.contains("PASS Work"));
        println!("{output}");
    }
}
