//! Generates and audits the CpuV3 fix16 FPU lookup ROM.

use std::fmt::Write as _;
use std::path::PathBuf;

const WORDS: usize = 1024;

fn quantize_unsigned(value: f64) -> u64 {
    value.round_ties_even().clamp(0.0, f64::from(u16::MAX)) as u64
}

fn generate() -> [u64; WORDS] {
    let mut words = [0; WORDS];
    for index in 0..256 {
        let even = 2 * index;
        let odd = even + 1;
        let sine = |sample: usize| {
            quantize_unsigned((sample as f64 * std::f64::consts::PI / 1024.0).sin() * 256.0)
        };
        words[index] = sine(even).min(255) | (sine(odd).min(255) << 8);
        let normalized = f64::from(256 + index as u16) / 256.0;
        words[256 + index] = quantize_unsigned(32768.0 / normalized);
        words[512 + index] = quantize_unsigned(32768.0 / normalized.sqrt());
        words[768 + index] = quantize_unsigned(32768.0 / (2.0 * normalized).sqrt());
    }
    words
}

fn render(words: &[u64; WORDS]) -> String {
    let mut output = String::from(
        "// Generated by `cargo run -p cpu-v3 --example generate_fpu_rom -- --write`.\n\
         // Layout: packed 512-sample sine quarter-wave, reciprocal, rsqrt-even, rsqrt-odd.\n\
         #[rustfmt::skip]\n\
         pub const FPU_ROM_WORDS: [u64; 1024] = [\n",
    );
    for chunk in words.chunks(8) {
        output.push_str("    ");
        for (index, word) in chunk.iter().enumerate() {
            if index != 0 {
                output.push(' ');
            }
            write!(output, "0x{word:04x},").unwrap();
        }
        output.push('\n');
    }
    output.push_str("];\n");
    output
}

fn main() {
    let destination = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("src")
        .join("architecture")
        .join("fpu_rom_data.rs");
    let rendered = render(&generate());
    if std::env::args()
        .skip(1)
        .any(|argument| argument == "--write")
    {
        std::fs::write(&destination, rendered).expect("write generated FPU ROM");
        println!("wrote {}", destination.display());
    } else {
        let checked_in = std::fs::read_to_string(&destination)
            .expect("read generated FPU ROM; run this example with --write first");
        assert_eq!(checked_in, rendered, "checked-in FPU ROM is stale");
        println!("FPU ROM is current: {}", destination.display());
    }
}
