`timescale 1ns/1ps
// Independent oracle data is generated by main.rs; this controller executes the DUT.
module LightingBoard(input wire clk,input wire [1:0] buttons,
    output wire [5:0] leds,output wire uart_tx);
wire logic_clk,locked;
`ifdef LIGHTING_BOARD_SIM
// Exercise the real 60/27 MHz domain crossing without the analog PLL model.
reg simulation_clock=0;
always #8.333 simulation_clock=~simulation_clock;
assign logic_clk=simulation_clock;
assign locked=1'b1;
`else
wire unused_p,unused_d,unused_d3;
rPLL pll(.CLKOUT(logic_clk),.LOCK(locked),.CLKOUTP(unused_p),.CLKOUTD(unused_d),.CLKOUTD3(unused_d3),
 .RESET(1'b0),.RESET_P(1'b0),.CLKIN(clk),.CLKFB(1'b0),.FBDSEL(6'b0),.IDSEL(6'b0),.ODSEL(6'b0),
 .PSDA(4'b0),.DUTYDA(4'b0),.FDLY(4'b0));
// 27 MHz * 20 / 9 = 60 MHz; ODIV16 keeps the VCO at 960 MHz.
defparam pll.FCLKIN="27",pll.IDIV_SEL=8,pll.FBDIV_SEL=19,pll.ODIV_SEL=16;
defparam pll.DYN_IDIV_SEL="false",pll.DYN_FBDIV_SEL="false",pll.DYN_ODIV_SEL="false";
defparam pll.CLKFB_SEL="internal",pll.PSDA_SEL="0000",pll.DYN_DA_EN="false",pll.DUTYDA_SEL="1000";
defparam pll.CLKOUT_FT_DIR=1'b1,pll.CLKOUTP_FT_DIR=1'b1,pll.CLKOUT_DLY_STEP=0,pll.CLKOUTP_DLY_STEP=0;
defparam pll.CLKOUT_BYPASS="false",pll.CLKOUTP_BYPASS="false",pll.CLKOUTD_BYPASS="false";
defparam pll.DYN_SDIV_SEL=2,pll.CLKOUTD_SRC="CLKOUT",pll.CLKOUTD3_SRC="CLKOUT",pll.DEVICE="GW2AR-18C";
`endif
reg [1:0] button_meta=0,button_sync=0;
reg lock_meta=0,lock_sync=0;
reg [5:0] startup=0;
always @(posedge logic_clk) begin
 button_meta<=buttons;button_sync<=button_meta;lock_meta<=locked;lock_sync<=lock_meta;
 if(!lock_sync || button_sync[0]) startup<=0;
 else if(startup!=63) startup<=startup+1'b1;
end
wire reset=!lock_sync || button_sync[0] || startup!=63;
reg [2:0] state=0;
reg done=0;
reg [7:0] status=0;
reg [4:0] context_index=0;
reg pass_index=0;
reg [9:0] send_index=0,receive_index=0;
reg [10:0] checked_outputs=0;
reg input_loaded=0;
reg [15:0] wall_cycle=0;
reg [12:0] watchdog=0;
wire ce=!done && wall_cycle[2:0]!=3'd2;
wire out_ready=wall_cycle[3:2]!=2'b00;
wire context_valid=state==0 && !reset && !done;
wire [15:0] context_epoch=16'h8200+{10'b0,pass_index,context_index};
wire [9:0] context_end={context_index+5'd1,5'b0};
wire in_valid=state==1 && input_loaded && send_index<context_end && !reset && !done;
wire context_ready,in_ready,out_valid;
wire [31:0] out_id;
wire [15:0] out_epoch;
wire [8:0] out_g,out_h;
reg signed [15:0] light_x,light_y,light_z,ray_x,ray_y,ray_k;
reg [8:0] ambient,directional;
reg [1:0] context_mode;
reg [4:0] context_code;
__UNIFORMS__
__ROMS__
reg [99:0] pixel_data=0;
reg [49:0] expected=0;
// Two independent synchronous reads, included in whole-board memory accounting.
always @(posedge logic_clk) begin pixel_data<=input_rom[send_index];expected<=golden_rom[receive_index];end
wire [31:0] in_id=pixel_data[99:68];
wire [35:0] in_row0={4'b0,pixel_data[23:12],4'b0,pixel_data[11:0],4'b0};
wire [35:0] in_row1={4'b0,pixel_data[51:36],pixel_data[35:24],4'b0};
wire [35:0] in_row2={20'b0,pixel_data[67:52]};
gpu_v2_lighting core(.clk(logic_clk),.reset(reset),.ce(ce),.context_valid(context_valid),.context_ready(context_ready),
 .context_epoch(context_epoch),.context_mode(context_mode),.context_code(context_code),
 .light_x(light_x),.light_y(light_y),.light_z(light_z),.ambient(ambient),.directional(directional),
 .ray_x(ray_x),.ray_y(ray_y),.ray_k(ray_k),.in_valid(in_valid),.in_ready(in_ready),.in_id(in_id),
 .in_row0(in_row0),.in_row1(in_row1),.in_row2(in_row2),.out_ready(out_ready),.out_valid(out_valid),
 .out_id(out_id),.out_epoch(out_epoch),.out_g(out_g),.out_h(out_h));
always @(posedge logic_clk) begin
 if(reset) begin
  state<=0;done<=0;status<=0;context_index<=0;pass_index<=0;send_index<=0;receive_index<=0;
  checked_outputs<=0;input_loaded<=0;wall_cycle<=0;watchdog<=0;
 end else if(!done) begin
  wall_cycle<=wall_cycle+1'b1;watchdog<=watchdog+1'b1;
  if(state==0 && ce && context_ready) begin state<=1;watchdog<=0;input_loaded<=0;end
  if(state==1) begin
   if(ce && in_valid && in_ready) begin send_index<=send_index+1'b1;input_loaded<=0;end
   else input_loaded<=1;
  end
  if(ce && out_valid && out_ready) begin
   if(state!=1 || receive_index>=send_index) begin done<=1;status<=4;end
   else if(out_id!=expected[31:0] || out_epoch!=context_epoch) begin done<=1;status<=2;end
   else if(out_g!=expected[40:32] || out_h!=expected[49:41]) begin done<=1;status<=1;end
   else begin
    receive_index<=receive_index+1'b1;checked_outputs<=checked_outputs+1'b1;
    if(receive_index==context_end-1'b1) begin
     watchdog<=0;state<=0;
     if(context_index==21) begin
      if(pass_index) begin done<=1;status<=0;state<=2;end
      else begin pass_index<=1;context_index<=0;send_index<=0;receive_index<=0;end
     end else context_index<=context_index+1'b1;
    end
   end
  end
  if(watchdog==13'd8191) begin done<=1;status<=3;end
 end
end
reg [31:0] heartbeat=0;
reg done_meta=0,done_sync=0;
reg [7:0] status_meta=0,status_sync=0;
always @(posedge clk) begin
 heartbeat<=heartbeat+1'b1;
 done_meta<=done;done_sync<=done_meta;status_meta<=status;status_sync<=status_meta;
end
wire uart_busy,frame_toggle;
__REPORTER__ reporter(.clk(clk),.report_enable(done_sync),.status(status_sync),
 .uart_tx(uart_tx),.uart_busy(uart_busy),.frame_toggle(frame_toggle));
assign leds={locked,uart_busy,frame_toggle,done_sync && status_sync==0,done_sync,heartbeat[23]};
endmodule
